address: "localhost"
port: "8080"

debug: true

test_db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    pass: "postgres"
    name: "FinanceTodo"

prod_db:
    host: "localhost"
    port: "5432"
    user: "postgres"
    pass: "postgres"
    name: "FinanceTodo"